apiVersion: v1
data:
  DB_HOST: db
  DB_NAME: postgres
  DB_PASSWORD: postgres
  DB_USERNAME: postgres
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-api-env
  name: api-env
